[workspace]
members = ["packages/proto-build", "packages/provwasm-common", "packages/provwasm-proc-macro", "packages/provwasm-std", "packages/provwasm-mocks"]
exclude = ["contracts"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false