[workspace]
members = ["packages/proto-build", "packages/provwasm-std-derive", "packages/provwasm-std"]
exclude = ["contracts"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false