[package]
name = "nft"
version = "2.1.0"
authors = ["Ken Talley <ktalley@provenance.io"]
edition = "2021"

exclude = [
  "scope.wasm",
  "checksums.txt",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = []

[dependencies]
cosmwasm-schema = { version = "1.2.5" }
cosmwasm-std = { version = "1.2.5", features = ["cosmwasm_1_1"] }
cosmwasm-storage = { version = "1.2.5" }
cw2 = "1.0.1"
cw721 = "0.17.0"
cw-ownable = "0.5.1"
cw-storage-plus = {version = "1.0.1", features = ["iterator"]}
cw-utils = {version = "1.0.1"}
provwasm-std = { path = "../../packages/provwasm-std" }
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
semver = "1"

[dev-dependencies]
serde_json = { version = "1.0.96", features = ["std"]}
provwasm-mocks = { path = "../../packages/provwasm-mocks" }
cw-multi-test = "0.16.2"