[package]
name = "provwasm-mocks"
version = "2.0.0"
authors = ["Ken Talley <ktalley@provenance.io"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/provenance-io/provwasm/tree/main/packages/mocks"
description = "Rust mocks that enable unit testing of CosmWasm smart contracts that interact with custom modules in the Provenance Blockchain"
readme = "README.md"
keywords = ["provenance", "blockchain", "smart-contracts", "defi", "finance"]
categories = ["development-tools::testing", "cryptography::cryptocurrencies", "wasm"]

[dependencies]
provwasm-std = { path = "../provwasm-std" }
cosmwasm-std = { version = "1.2.5", default-features = false }
schemars = "0.8.1"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
