[package]
name = "provwasm-mocks"
version = "2.2.0"
authors = ["Ken Talley <4344285+kwtalley@users.noreply.github.com"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/provenance-io/provwasm/tree/main/packages/provwasm-mocks"
description = "Rust mocks that enable unit testing of CosmWasm smart contracts that interact with custom modules in the Provenance Blockchain"
readme = "README.md"
keywords = ["provenance", "blockchain", "smart-contracts", "defi", "finance"]
categories = ["development-tools::testing", "cryptography::cryptocurrencies", "wasm"]

[dependencies]
provwasm-common = { workspace = true }
provwasm-std = { workspace = true }
cosmwasm-std = { workspace = true, default-features = false }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
