[package]
name = "proto-build"
version = "2.0.0"
authors = ["Ken Talley <ktalley@figure.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
heck = "0.4.1"
itertools = "0.10.5"
log = "0.4.17"
pretty_env_logger = "0.4.0"
prettyplease = "0.1.23"
prost = "0.11.6"
prost-build = "0.11.6"
prost-types = "0.11.6"
regex = "1.7.1"
syn = {version = "1.0.107", features = ["full", "parsing"]}
tonic = "0.8.3"
tonic-build = "0.8.4"
walkdir = "2.3.2"
