[package]
name = "proto-build"
version = "0.1.0"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = ["Ken Talley <4344285+kwtalley@users.noreply.github.com"]
publish = false

[dependencies]
heck = "0.4.0"
itertools = "0.11.0"
log = "0.4.17"
pretty_env_logger = "0.5.0"
prettyplease = "0.1.16"
proc-macro2 = "1.0.52"
prost = { workspace = true }
prost-build = { workspace = true }
prost-types = { workspace = true }
quote = "1.0.26"
regex = "1"
syn = { version = "1.0.109", features = ["full", "parsing", "extra-traits"] }
tonic = "0.7"
tonic-build = "0.7"
walkdir = "2"