.PHONY: all
all: attrs ibc marker msgfees name scope tutorial

.PHONY: attrs
attrs:
	@make -C attrs

.PHONY: ibc
ibc:
	@make -C ibc

.PHONY: marker
marker:
	@make -C marker

.PHONY: msgfees
msgfees:
	@make -C msgfees

.PHONY: name
name:
	@make -C name

.PHONY: scope
scope:
	@make -C scope

.PHONY: tutorial
tutorial:
	@make -C tutorial

.PHONY: clean
clean:
	@make -C attrs clean
	@make -C ibc clean
	@make -C marker clean
	@make -C msgfees clean
	@make -C name clean
	@make -C scope clean
