.PHONY: all
all: attrs marker name

.PHONY: attrs
attrs:
	@make -C attrs

.PHONY: marker
marker:
	@make -C marker

.PHONY: name
name:
	@make -C name

.PHONY: clean
clean:
	@make -C attrs clean
	@make -C marker clean
	@make -C name clean
