[package]
name = "provwasm-std-derive"
version = "2.0.0"
authors = ["Ken Talley <ktalley@figure.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/provenance-io/provwasm/tree/main/packages/provwasm-std-derive"
description = "Rust macros that simplify query and response types for Provenance Blockchain smart contracts"
keywords = ["provenance", "blockchain", "smart-contracts", "defi", "finance"]
categories = ["api-bindings", "cryptography::cryptocurrencies", "wasm"]

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.5"
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = "1.0.107"

[dev-dependencies]
cosmwasm-std = {version = "1.1.2", default-features = false}
prost = "0.11.6"
serde = "1.0.152"
trybuild = {version = "1.0.77", features = ["diff"]}
